# Generated by Django 2.1.1 on 2018-09-08 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0003_readdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readdetail',
            old_name='contenttype',
            new_name='content_type',
        ),
    ]
